Update Rocket.Chat to 0.72.3

diff --git a/rocketchat b/rocketchat
--- a/rocketchat
+++ b/rocketchat
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-ROCKETCHAT_VERSION='0.72.0'
-ROCKETCHAT_SHA256='1a872213a57c8ac973153be45aa5cec10f6d89e09e7bbf673c6cf976d1161ab8'
+ROCKETCHAT_VERSION='0.72.3'
+ROCKETCHAT_SHA256='65eee33823aa9171e6dfbfee824c81a80e4d2d8fe46fd86ec51e7e0f230e805e'
 
 export CXX=clang++
 
@@ -71,6 +71,9 @@ pkg upgrade -y pkg 2>&1 || error "The package management tool could not be upgra
 # Install required packages
 echo "Installing required packages..."
 pkg install -y jq mongodb36 node8 npm-node8 pkgconf python python2 python27 vips 2>&1 || error "Failed to install required packages."
+
+# Upgrade the node package manager, if required
+npm install -g npm 2>&1 || error "The node package manager could not be upgraded."
 
 # Remove previous Rocket.Chat build directory
 rm -rf /usr/local/rocketchat/build 2>&1 || error "Failed to remove previous Rocket.Chat build directory."
