Update Rocket.Chat to 0.72.0 and grpc to 1.16.1

diff --git a/rocketchat b/rocketchat
--- a/rocketchat
+++ b/rocketchat
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-ROCKETCHAT_VERSION='0.71.0'
-ROCKETCHAT_SHA256='8bc807b6536cfad5377dbec991922eeb91cdfb593951a2b18774a3e42c3b7561'
+ROCKETCHAT_VERSION='0.72.0'
+ROCKETCHAT_SHA256='1a872213a57c8ac973153be45aa5cec10f6d89e09e7bbf673c6cf976d1161ab8'
 
 export CXX=clang++
 
@@ -77,11 +77,13 @@ rm -rf /usr/local/rocketchat/build
 echo "Creating required directories..."
 mkdir -p /var/log/rocketchat /var/run/rocketchat /usr/local/etc/newsyslog.conf.d /usr/local/rocketchat/build /usr/local/rocketchat/uploads >/dev/null 2>&1 || error "Failed to create required directories."
 
-# Create the Rocket.Chat user and group (rocketchat)
+# Create the Rocket.Chat group (rocketchat)
 getent group rocketchat >/dev/null 2>&1 || {
     echo "Creating rocketchat group..."
     pw groupadd rocketchat >/dev/null 2>&1 || error "Failed to add rocketchat group."
 }
+
+# Create the Rocket.Chat user (rocketchat)
 id -u rocketchat >/dev/null 2>&1 || {
     echo "Creating rocketchat user..."
     pw useradd rocketchat -g rocketchat -c "Rocket.Chat" -d /usr/local/rocketchat -s /usr/sbin/nologin >/dev/null 2>&1 || error "Failed to add rocketchat use."
@@ -97,12 +99,12 @@ sha256 -c $ROCKETCHAT_SHA256 /usr/local/rocketchat/build/rocketchat.tgz >/dev/nu
 # Patch web.browser files
 patchWebFiles "/usr/local/rocketchat/build/bundle/programs/web.browser"
 
-# Patch web.cordova files
-patchWebFiles "/usr/local/rocketchat/build/bundle/programs/web.cordova"
+# Patch web.browser.legacy files
+patchWebFiles "/usr/local/rocketchat/build/bundle/programs/web.browser.legacy"
 
 # Patch google-gax/package.json as grpc <1.15.0 doesn't compile on FreeBSD
 echo "Patching package.json for google-gax..."
-sed -i '.bak' "s/\"grpc\": \"^1.10.0\",/\"grpc\": \"^1.15.1\",/g" /usr/local/rocketchat/build/bundle/programs/server/npm/node_modules/google-gax/package.json >/dev/null 2>&1 || error "Failed to execute sed. (5)"
+sed -i '.bak' "s/\"grpc\": \"^1.10.0\",/\"grpc\": \"^1.16.1\",/g" /usr/local/rocketchat/build/bundle/programs/server/npm/node_modules/google-gax/package.json >/dev/null 2>&1 || error "Failed to execute sed. (5)"
 
 # Remove the included version of the grpc module
 echo "Removing included grpc module..."
